### ISSUE TITLE
Are there pre-trained models and evaluation scripts to play with the inference on sample data? 

### ISSUE THREAD

**Issue by ry4nzhu** [mercedes-benz/selfsupervised_flow#6]
Hi, thanks for releasing this code! I want to know if you plan to release the pre-trained models and scripts to perform some example inference results (like Figure 3 in the paper)?

**Comment by baurst** [comment]
Thank you for your issue. 

The visualizations have been created using [blender_kitti](https://github.com/risteon/blender_kitti). I recommend to export the point clouds and flow vectors as .npz and then adapt this script here [blender_kitti/blender_kitti_examples/example_render_kitti.py#L81](https://github.com/risteon/blender_kitti/blob/ca9effd8142d7633ebb7af19f6ab628328245809/blender_kitti_examples/example_render_kitti.py#L81) to visualize flow maps.  We will not release pre-trained checkpoints.

Hope this helps, and good luck with your project.
